// import React, { useState, useEffect } from 'react';
// import { 
//   Clock, Users, Calendar, Filter, Search, Plus, Download, 
//   Edit, Trash2, X, Save, LogIn, LogOut, Upload, Coffee,
//   Smoking, DoorOpen, Prayer, Users2, FileText, Target,
//   TrendingUp,  MapPin, 
//   BarChart3, PieChart, Zap, Eye, EyeOff,
//   Cigarette,
//   ChurchIcon
// } from 'lucide-react';

// // Employee Activity Tracker Component
// export function TimeTracker() {
//   const [activities, setActivities] = useState([
//     {
//       id: 1,
//       employeeId: 1,
//       employeeName: 'John Smith',
//       employeeAvatar: 'JS',
//       department: 'Engineering',
//       activityType: 'check_in',
//       action: 'Checked in to work',
//       description: 'Started work day',
//       timestamp: new Date().setHours(9, 0, 0, 0), // 9:00 AM today
//       duration: null,
//       status: 'completed',
//       location: 'Main Office',
//       device: 'Desktop',
//       autoGenerated: false
//     },
//     {
//       id: 2,
//       employeeId: 2,
//       employeeName: 'Sarah Johnson',
//       employeeAvatar: 'SJ',
//       department: 'Marketing',
//       activityType: 'file_upload',
//       action: 'Uploaded project files',
//       description: 'Q4 marketing campaign assets',
//       timestamp: new Date().setHours(10, 30, 0, 0),
//       duration: null,
//       status: 'completed',
//       location: 'Remote',
//       device: 'Laptop',
//       autoGenerated: false
//     },
//     {
//       id: 3,
//       employeeId: 1,
//       employeeName: 'John Smith',
//       employeeAvatar: 'JS',
//       department: 'Engineering',
//       activityType: 'coffee_break',
//       action: 'Coffee break',
//       description: '15 minute break',
//       timestamp: new Date().setHours(10, 45, 0, 0),
//       duration: 900, // 15 minutes in seconds
//       status: 'completed',
//       location: 'Break Room',
//       device: 'N/A',
//       autoGenerated: false
//     },
//     {
//       id: 4,
//       employeeId: 3,
//       employeeName: 'Mike Chen',
//       employeeAvatar: 'MC',
//       department: 'Design',
//       activityType: 'team_meeting',
//       action: 'Team meeting',
//       description: 'Weekly design review',
//       timestamp: new Date().setHours(11, 0, 0, 0),
//       duration: 1800, // 30 minutes
//       status: 'completed',
//       location: 'Conference Room B',
//       device: 'Meeting System',
//       autoGenerated: false
//     },
//     {
//       id: 5,
//       employeeId: 2,
//       employeeName: 'Sarah Johnson',
//       employeeAvatar: 'SJ',
//       department: 'Marketing',
//       activityType: 'lunch_break',
//       action: 'Lunch break',
//       description: 'Lunch break',
//       timestamp: new Date().setHours(12, 30, 0, 0),
//       duration: 3600, // 1 hour
//       status: 'completed',
//       location: 'Cafeteria',
//       device: 'N/A',
//       autoGenerated: false
//     }
//   ]);

//   const [employees] = useState([
//     { id: 1, name: 'John Smith', department: 'Engineering', position: 'Senior Developer' },
//     { id: 2, name: 'Sarah Johnson', department: 'Marketing', position: 'Marketing Manager' },
//     { id: 3, name: 'Mike Chen', department: 'Design', position: 'UI/UX Designer' },
//     { id: 4, name: 'Emily Davis', department: 'HR', position: 'HR Manager' },
//     { id: 5, name: 'Alex Wilson', department: 'Sales', position: 'Sales Executive' }
//   ]);

//   const [filter, setFilter] = useState('all');
//   const [departmentFilter, setDepartmentFilter] = useState('all');
//   const [timeRange, setTimeRange] = useState('today');
//   const [searchTerm, setSearchTerm] = useState('');
//   const [selectedActivity, setSelectedActivity] = useState(null);
//   const [showAddModal, setShowAddModal] = useState(false);
//   const [editingActivity, setEditingActivity] = useState(null);
//   const [currentTime, setCurrentTime] = useState(new Date());
//   const [realTimeActivities, setRealTimeActivities] = useState([]);

//   // Update current time every second
//   useEffect(() => {
//     const timer = setInterval(() => {
//       setCurrentTime(new Date());
//     }, 1000);
//     return () => clearInterval(timer);
//   }, []);

//   // Simulate real-time employee activities
//   useEffect(() => {
//     const activityTimer = setInterval(() => {
//       const shouldAddActivity = Math.random() > 0.8; // 20% chance
//       if (shouldAddActivity) {
//         const newActivity = generateRandomActivity();
//         setRealTimeActivities(prev => [newActivity, ...prev.slice(0, 4)]); // Keep last 5
//         setActivities(prev => [newActivity, ...prev]);
//       }
//     }, 10000); // Check every 10 seconds

//     return () => clearInterval(activityTimer);
//   }, []);

//   const generateRandomActivity = () => {
//     const activityTypes = [
//       { type: 'coffee_break', action: 'Coffee break', duration: 600 },
//       { type: 'smoking_break', action: 'Smoking break', duration: 300 },
//       { type: 'washroom_break', action: 'Washroom break', duration: 300 },
//       { type: 'prayer_break', action: 'Prayer break', duration: 900 },
//       { type: 'file_upload', action: 'Uploaded files', duration: null }
//     ];

//     const randomEmployee = employees[Math.floor(Math.random() * employees.length)];
//     const randomType = activityTypes[Math.floor(Math.random() * activityTypes.length)];
    
//     return {
//       id: Date.now(),
//       employeeId: randomEmployee.id,
//       employeeName: randomEmployee.name,
//       employeeAvatar: randomEmployee.name.split(' ').map(n => n[0]).join(''),
//       department: randomEmployee.department,
//       activityType: randomType.type,
//       action: randomType.action,
//       description: `Automated ${randomType.action.toLowerCase()}`,
//       timestamp: new Date(),
//       duration: randomType.duration,
//       status: 'completed',
//       location: ['Main Office', 'Remote', 'Break Room'][Math.floor(Math.random() * 3)],
//       device: ['Desktop', 'Laptop', 'Mobile'][Math.floor(Math.random() * 3)],
//       autoGenerated: true
//     };
//   };

//   // Filter activities
//   const filteredActivities = activities.filter(activity => {
//     if (filter !== 'all' && activity.activityType !== filter) return false;
//     if (departmentFilter !== 'all' && activity.department !== departmentFilter) return false;
//     if (searchTerm && !activity.employeeName.toLowerCase().includes(searchTerm.toLowerCase()) && 
//         !activity.description.toLowerCase().includes(searchTerm.toLowerCase())) return false;
    
//     const activityDate = new Date(activity.timestamp);
//     const now = new Date();
    
//     switch (timeRange) {
//       case 'today':
//         return activityDate.toDateString() === now.toDateString();
//       case 'week':
//         const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
//         return activityDate >= weekAgo;
//       case 'month':
//         const monthAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
//         return activityDate >= monthAgo;
//       default:
//         return true;
//     }
//   });

//   // Calculate statistics
//   const stats = {
//     totalActivities: activities.length,
//     activeEmployees: new Set(activities.filter(a => {
//       const activityTime = new Date(a.timestamp);
//       return (currentTime - activityTime) < 30 * 60 * 1000; // Active in last 30 minutes
//     }).map(a => a.employeeId)).size,
//     checkedInEmployees: activities.filter(a => 
//       a.activityType === 'check_in' && 
//       new Date(a.timestamp).toDateString() === new Date().toDateString()
//     ).length,
//     currentBreaks: activities.filter(a => 
//       ['coffee_break', 'smoking_break', 'washroom_break', 'prayer_break', 'lunch_break'].includes(a.activityType) &&
//       new Date(a.timestamp).toDateString() === new Date().toDateString()
//     ).length
//   };

//   const getActivityIcon = (type) => {
//     const icons = {
//       check_in: <LogIn className="h-4 w-4" />,
//       check_out: <LogOut className="h-4 w-4" />,
//       file_upload: <Upload className="h-4 w-4" />,
//       coffee_break: <Coffee className="h-4 w-4" />,
//       smoking_break: <Cigarette className="h-4 w-4" />,
//       washroom_break: <DoorOpen className="h-4 w-4" />,
//       prayer_break: <ChurchIcon className="h-4 w-4" />,
//       lunch_break: <Coffee className="h-4 w-4" />,
//       team_meeting: <Users2 className="h-4 w-4" />,
//       hr_update: <FileText className="h-4 w-4" />,
//       project_timeline: <Target className="h-4 w-4" />
//     };
//     return icons[type] || <Clock className="h-4 w-4" />;
//   };

//   const getActivityColor = (type) => {
//     const colors = {
//       check_in: 'bg-green-100 text-green-800 border-green-200',
//       check_out: 'bg-red-100 text-red-800 border-red-200',
//       file_upload: 'bg-blue-100 text-blue-800 border-blue-200',
//       coffee_break: 'bg-orange-100 text-orange-800 border-orange-200',
//       smoking_break: 'bg-yellow-100 text-yellow-800 border-yellow-200',
//       washroom_break: 'bg-purple-100 text-purple-800 border-purple-200',
//       prayer_break: 'bg-indigo-100 text-indigo-800 border-indigo-200',
//       lunch_break: 'bg-pink-100 text-pink-800 border-pink-200',
//       team_meeting: 'bg-teal-100 text-teal-800 border-teal-200',
//       hr_update: 'bg-cyan-100 text-cyan-800 border-cyan-200',
//       project_timeline: 'bg-amber-100 text-amber-800 border-amber-200'
//     };
//     return colors[type] || 'bg-gray-100 text-gray-800 border-gray-200';
//   };

//   const formatDuration = (seconds) => {
//     if (!seconds) return null;
//     const minutes = Math.floor(seconds / 60);
//     return `${minutes}m`;
//   };

//   const formatTimeAgo = (timestamp) => {
//     const diff = currentTime - new Date(timestamp);
//     const minutes = Math.floor(diff / 60000);
//     const hours = Math.floor(diff / 3600000);
    
//     if (minutes < 1) return 'Just now';
//     if (minutes < 60) return `${minutes}m ago`;
//     if (hours < 24) return `${hours}h ago`;
//     return new Date(timestamp).toLocaleDateString();
//   };

//   // CRUD Operations
//   const handleAddActivity = (activityData) => {
//     const newActivity = {
//       id: Date.now(),
//       timestamp: new Date(),
//       status: 'completed',
//       autoGenerated: false,
//       ...activityData
//     };
//     setActivities(prev => [newActivity, ...prev]);
//     setShowAddModal(false);
//   };

//   const handleEditActivity = (activityData) => {
//     setActivities(prev => prev.map(activity => 
//       activity.id === activityData.id ? { ...activity, ...activityData } : activity
//     ));
//     setEditingActivity(null);
//   };

//   const handleDeleteActivity = (activityId) => {
//     setActivities(prev => prev.filter(activity => activity.id !== activityId));
//     if (selectedActivity?.id === activityId) {
//       setSelectedActivity(null);
//     }
//   };

//   const handleQuickCheckIn = (employeeId) => {
//     const employee = employees.find(emp => emp.id === employeeId);
//     const newActivity = {
//       id: Date.now(),
//       employeeId: employee.id,
//       employeeName: employee.name,
//       employeeAvatar: employee.name.split(' ').map(n => n[0]).join(''),
//       department: employee.department,
//       activityType: 'check_in',
//       action: 'Checked in to work',
//       description: 'Started work day',
//       timestamp: new Date(),
//       duration: null,
//       status: 'completed',
//       location: 'Main Office',
//       device: 'System',
//       autoGenerated: false
//     };
//     setActivities(prev => [newActivity, ...prev]);
//   };

//   const handleQuickBreak = (employeeId, breakType) => {
//     const employee = employees.find(emp => emp.id === employeeId);
//     const breakConfig = {
//       coffee_break: { action: 'Coffee break', duration: 600 },
//       lunch_break: { action: 'Lunch break', duration: 3600 },
//       smoking_break: { action: 'Smoking break', duration: 300 }
//     };

//     const config = breakConfig[breakType];
//     const newActivity = {
//       id: Date.now(),
//       employeeId: employee.id,
//       employeeName: employee.name,
//       employeeAvatar: employee.name.split(' ').map(n => n[0]).join(''),
//       department: employee.department,
//       activityType: breakType,
//       action: config.action,
//       description: `${config.action} started`,
//       timestamp: new Date(),
//       duration: config.duration,
//       status: 'completed',
//       location: 'Break Area',
//       device: 'System',
//       autoGenerated: false
//     };
//     setActivities(prev => [newActivity, ...prev]);
//   };

//   return (
//     <div className="min-h-screen bg-gradient-to-br from-gray-50 to-blue-50 p-6">
//       <div className="max-w-7xl mx-auto">
//         {/* Header */}
//         <div className="mb-8">
//           <div className="flex justify-between items-start mb-6">
//             <div>
//               <h1 className="text-3xl font-bold text-gray-900">Employee Activity Tracker</h1>
//               <p className="text-gray-600 mt-2">Monitor employee check-ins, breaks, and work activities</p>
//             </div>
//             <div className="flex gap-3">
//               <button 
//                 onClick={() => setShowAddModal(true)}
//                 className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-xl hover:bg-blue-700 transition duration-200"
//               >
//                 <Plus className="h-4 w-4" />
//                 Log Activity
//               </button>
//             </div>
//           </div>

//           {/* Stats Overview */}
//           <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
//             <div className="bg-white rounded-2xl p-6 border border-gray-200 shadow-sm">
//               <div className="flex items-center justify-between">
//                 <div>
//                   <p className="text-sm text-gray-600">Total Activities</p>
//                   <p className="text-2xl font-bold text-gray-900">{stats.totalActivities}</p>
//                 </div>
//                 <div className="p-3 bg-blue-100 rounded-xl">
//                   <Activity className="h-6 w-6 text-blue-600" />
//                 </div>
//               </div>
//               <div className="mt-2 text-sm text-green-600 flex items-center">
//                 <TrendingUp className="h-4 w-4 mr-1" />
//                 +{realTimeActivities.length} today
//               </div>
//             </div>

//             <div className="bg-white rounded-2xl p-6 border border-gray-200 shadow-sm">
//               <div className="flex items-center justify-between">
//                 <div>
//                   <p className="text-sm text-gray-600">Active Employees</p>
//                   <p className="text-2xl font-bold text-gray-900">{stats.activeEmployees}</p>
//                 </div>
//                 <div className="p-3 bg-green-100 rounded-xl">
//                   <Users className="h-6 w-6 text-green-600" />
//                 </div>
//               </div>
//               <div className="mt-2 text-sm text-gray-600">Last 30 minutes</div>
//             </div>

//             <div className="bg-white rounded-2xl p-6 border border-gray-200 shadow-sm">
//               <div className="flex items-center justify-between">
//                 <div>
//                   <p className="text-sm text-gray-600">Checked In</p>
//                   <p className="text-2xl font-bold text-gray-900">{stats.checkedInEmployees}</p>
//                 </div>
//                 <div className="p-3 bg-orange-100 rounded-xl">
//                   <LogIn className="h-6 w-6 text-orange-600" />
//                 </div>
//               </div>
//               <div className="mt-2 text-sm text-gray-600">Today</div>
//             </div>

//             <div className="bg-white rounded-2xl p-6 border border-gray-200 shadow-sm">
//               <div className="flex items-center justify-between">
//                 <div>
//                   <p className="text-sm text-gray-600">Current Breaks</p>
//                   <p className="text-2xl font-bold text-gray-900">{stats.currentBreaks}</p>
//                 </div>
//                 <div className="p-3 bg-purple-100 rounded-xl">
//                   <Coffee className="h-6 w-6 text-purple-600" />
//                 </div>
//               </div>
//               <div className="mt-2 text-sm text-gray-600">Ongoing</div>
//             </div>
//           </div>
//         </div>

//         {/* Quick Actions */}
//         <div className="bg-white rounded-2xl p-6 border border-gray-200 mb-6">
//           <h3 className="text-lg font-semibold text-gray-900 mb-4">Quick Actions</h3>
//           <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-3">
//             {employees.slice(0, 6).map(employee => (
//               <div key={employee.id} className="text-center">
//                 <div className="bg-gray-100 rounded-xl p-3 mb-2">
//                   <div className="w-12 h-12 bg-gradient-to-r from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white text-sm font-medium mx-auto">
//                     {employee.name.split(' ').map(n => n[0]).join('')}
//                   </div>
//                 </div>
//                 <p className="text-sm font-medium text-gray-900 truncate">{employee.name.split(' ')[0]}</p>
//                 <div className="flex gap-1 mt-2">
//                   <button 
//                     onClick={() => handleQuickCheckIn(employee.id)}
//                     className="flex-1 px-2 py-1 bg-green-500 text-white text-xs rounded-lg hover:bg-green-600"
//                   >
//                     Check In
//                   </button>
//                   <button 
//                     onClick={() => handleQuickBreak(employee.id, 'coffee_break')}
//                     className="flex-1 px-2 py-1 bg-orange-500 text-white text-xs rounded-lg hover:bg-orange-600"
//                   >
//                     Break
//                   </button>
//                 </div>
//               </div>
//             ))}
//           </div>
//         </div>

//         {/* Controls and Filters */}
//         <div className="bg-white rounded-2xl p-6 border border-gray-200 mb-6">
//           <div className="flex flex-col lg:flex-row gap-4 justify-between items-start lg:items-center">
//             <div className="flex flex-wrap gap-3">
//               <select 
//                 value={filter}
//                 onChange={(e) => setFilter(e.target.value)}
//                 className="px-3 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500"
//               >
//                 <option value="all">All Activities</option>
//                 <option value="check_in">Check In</option>
//                 <option value="check_out">Check Out</option>
//                 <option value="file_upload">File Upload</option>
//                 <option value="coffee_break">Coffee Break</option>
//                 <option value="lunch_break">Lunch Break</option>
//                 <option value="smoking_break">Smoking Break</option>
//                 <option value="washroom_break">Washroom Break</option>
//                 <option value="prayer_break">Prayer Break</option>
//                 <option value="team_meeting">Team Meeting</option>
//                 <option value="hr_update">HR Update</option>
//                 <option value="project_timeline">Project Timeline</option>
//               </select>

//               <select 
//                 value={departmentFilter}
//                 onChange={(e) => setDepartmentFilter(e.target.value)}
//                 className="px-3 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500"
//               >
//                 <option value="all">All Departments</option>
//                 <option value="Engineering">Engineering</option>
//                 <option value="Marketing">Marketing</option>
//                 <option value="Design">Design</option>
//                 <option value="HR">HR</option>
//                 <option value="Sales">Sales</option>
//               </select>

//               <select 
//                 value={timeRange}
//                 onChange={(e) => setTimeRange(e.target.value)}
//                 className="px-3 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500"
//               >
//                 <option value="today">Today</option>
//                 <option value="week">This Week</option>
//                 <option value="month">This Month</option>
//                 <option value="all">All Time</option>
//               </select>
//             </div>

//             <div className="flex flex-wrap gap-3">
//               <div className="relative">
//                 <Search className="h-4 w-4 absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
//                 <input
//                   type="text"
//                   placeholder="Search employees or activities..."
//                   value={searchTerm}
//                   onChange={(e) => setSearchTerm(e.target.value)}
//                   className="pl-10 pr-4 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
//                 />
//               </div>
//             </div>
//           </div>
//         </div>

//         {/* Real-time Activities Banner */}
//         {realTimeActivities.length > 0 && (
//           <div className="bg-blue-50 border border-blue-200 rounded-2xl p-4 mb-6">
//             <div className="flex items-center justify-between">
//               <div className="flex items-center gap-2">
//                 <Zap className="h-5 w-5 text-blue-600" />
//                 <span className="font-medium text-blue-800">Recent Activities</span>
//                 <span className="text-blue-600 text-sm">({realTimeActivities.length} new)</span>
//               </div>
//               <button 
//                 onClick={() => setRealTimeActivities([])}
//                 className="text-blue-600 hover:text-blue-800"
//               >
//                 <X className="h-4 w-4" />
//               </button>
//             </div>
//             <div className="flex flex-wrap gap-2 mt-2">
//               {realTimeActivities.map(activity => (
//                 <span key={activity.id} className="text-xs bg-white px-2 py-1 rounded-lg border">
//                   {activity.employeeName} - {activity.action}
//                 </span>
//               ))}
//             </div>
//           </div>
//         )}

//         {/* Activities Timeline */}
//         <div className="bg-white rounded-2xl border border-gray-200 overflow-hidden">
//           <div className="p-6 border-b border-gray-200">
//             <div className="flex justify-between items-center">
//               <div>
//                 <h2 className="text-xl font-semibold text-gray-900">Employee Activities</h2>
//                 <p className="text-gray-600 text-sm">
//                   {filteredActivities.length} activities found
//                   {searchTerm && ` for "${searchTerm}"`}
//                 </p>
//               </div>
//               <div className="text-sm text-gray-500">
//                 Last update: {currentTime.toLocaleTimeString()}
//               </div>
//             </div>
//           </div>
          
//           <div className="divide-y divide-gray-100 max-h-[600px] overflow-y-auto">
//             {filteredActivities.map((activity, index) => (
//               <div 
//                 key={activity.id}
//                 className="p-6 hover:bg-gray-50 transition duration-200 cursor-pointer group"
//                 onClick={() => setSelectedActivity(activity)}
//               >
//                 <div className="flex gap-4">
//                   {/* Activity Icon */}
//                   <div className="flex flex-col items-center">
//                     <div className={`w-12 h-12 rounded-full flex items-center justify-center border-2 ${getActivityColor(activity.activityType)}`}>
//                       {getActivityIcon(activity.activityType)}
//                     </div>
//                     {index < filteredActivities.length - 1 && (
//                       <div className="w-0.5 h-full bg-gray-200 mt-2"></div>
//                     )}
//                   </div>

//                   {/* Activity Content */}
//                   <div className="flex-1 min-w-0">
//                     <div className="flex items-start justify-between mb-2">
//                       <div>
//                         <h3 className="font-semibold text-gray-900">{activity.action}</h3>
//                         <p className="text-gray-600 text-sm">{activity.description}</p>
//                       </div>
//                       <div className="flex items-center gap-2">
//                         <span className="text-sm text-gray-500">
//                           {formatTimeAgo(activity.timestamp)}
//                         </span>
//                       </div>
//                     </div>

//                     <div className="flex items-center gap-4 text-sm text-gray-500">
//                       <div className="flex items-center gap-1">
//                         <div className="w-6 h-6 bg-gradient-to-r from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white text-xs font-medium">
//                           {activity.employeeAvatar}
//                         </div>
//                         <span>{activity.employeeName}</span>
//                         <span className="text-xs bg-gray-100 px-2 py-1 rounded">{activity.department}</span>
//                       </div>
                      
//                       <div className="flex items-center gap-1">
//                         <MapPin className="h-3 w-3" />
//                         <span>{activity.location}</span>
//                       </div>
                      
//                       {activity.duration && (
//                         <div className="flex items-center gap-1">
//                           <Clock className="h-3 w-3" />
//                           <span>{formatDuration(activity.duration)}</span>
//                         </div>
//                       )}

//                       {activity.autoGenerated && (
//                         <span className="text-xs bg-yellow-100 text-yellow-800 px-2 py-1 rounded">
//                           Auto
//                         </span>
//                       )}
//                     </div>

//                     {/* Action Buttons */}
//                     <div className="flex gap-2 mt-3 opacity-0 group-hover:opacity-100 transition-opacity">
//                       <button 
//                         onClick={(e) => {
//                           e.stopPropagation();
//                           setEditingActivity(activity);
//                         }}
//                         className="px-2 py-1 text-xs bg-blue-100 text-blue-700 rounded-lg hover:bg-blue-200 transition duration-200"
//                       >
//                         Edit
//                       </button>
//                       <button 
//                         onClick={(e) => {
//                           e.stopPropagation();
//                           handleDeleteActivity(activity.id);
//                         }}
//                         className="px-2 py-1 text-xs bg-red-100 text-red-700 rounded-lg hover:bg-red-200 transition duration-200"
//                       >
//                         Delete
//                       </button>
//                     </div>
//                   </div>
//                 </div>
//               </div>
//             ))}
//           </div>

//           {filteredActivities.length === 0 && (
//             <div className="text-center py-12">
//               <Clock className="h-16 w-16 mx-auto mb-4 text-gray-400" />
//               <h3 className="text-lg font-medium text-gray-900 mb-2">No activities found</h3>
//               <p className="text-gray-600">No activities match your current filters.</p>
//             </div>
//           )}
//         </div>

//         {/* Activity Details Modal */}
//         {selectedActivity && (
//           <ActivityDetailsModal 
//             activity={selectedActivity}
//             onClose={() => setSelectedActivity(null)}
//             onEdit={() => setEditingActivity(selectedActivity)}
//             onDelete={() => handleDeleteActivity(selectedActivity.id)}
//           />
//         )}

//         {/* Add/Edit Activity Modal */}
//         {showAddModal && (
//           <ActivityModal 
//             onClose={() => setShowAddModal(false)}
//             onSave={handleAddActivity}
//             employees={employees}
//             mode="add"
//           />
//         )}

//         {editingActivity && (
//           <ActivityModal 
//             onClose={() => setEditingActivity(null)}
//             onSave={handleEditActivity}
//             activity={editingActivity}
//             employees={employees}
//             mode="edit"
//           />
//         )}
//       </div>
//     </div>
//   );
// }

// // Activity Details Modal
// function ActivityDetailsModal({ activity, onClose, onEdit, onDelete }) {
//   return (
//     <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
//       <div className="bg-white rounded-2xl w-full max-w-md">
//         <div className="flex justify-between items-center p-6 border-b border-gray-200">
//           <h3 className="text-lg font-semibold text-gray-900">Activity Details</h3>
//           <button onClick={onClose} className="p-1 hover:bg-gray-100 rounded-lg">
//             <X className="h-5 w-5" />
//           </button>
//         </div>
        
//         <div className="p-6 space-y-4">
//           <div className="flex items-center gap-3">
//             <div className={`w-12 h-12 rounded-full flex items-center justify-center border-2 ${getActivityColor(activity.activityType)}`}>
//               {getActivityIcon(activity.activityType)}
//             </div>
//             <div>
//               <h4 className="font-semibold text-gray-900">{activity.action}</h4>
//               <p className="text-gray-600 text-sm">{activity.description}</p>
//             </div>
//           </div>

//           <div className="grid grid-cols-2 gap-4 text-sm">
//             <div>
//               <label className="font-medium text-gray-700">Employee</label>
//               <p className="text-gray-900">{activity.employeeName}</p>
//             </div>
//             <div>
//               <label className="font-medium text-gray-700">Department</label>
//               <p className="text-gray-900">{activity.department}</p>
//             </div>
//             <div>
//               <label className="font-medium text-gray-700">Location</label>
//               <p className="text-gray-900">{activity.location}</p>
//             </div>
//             <div>
//               <label className="font-medium text-gray-700">Device</label>
//               <p className="text-gray-900">{activity.device}</p>
//             </div>
//             <div className="col-span-2">
//               <label className="font-medium text-gray-700">Time</label>
//               <p className="text-gray-900">{new Date(activity.timestamp).toLocaleString()}</p>
//             </div>
//             {activity.duration && (
//               <div className="col-span-2">
//                 <label className="font-medium text-gray-700">Duration</label>
//                 <p className="text-gray-900">{formatDuration(activity.duration)}</p>
//               </div>
//             )}
//           </div>

//           <div className="flex gap-2 pt-4">
//             <button 
//               onClick={onEdit}
//               className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-xl hover:bg-blue-700 transition duration-200"
//             >
//               Edit
//             </button>
//             <button 
//               onClick={onDelete}
//               className="px-4 py-2 bg-red-600 text-white rounded-xl hover:bg-red-700 transition duration-200"
//             >
//               Delete
//             </button>
//           </div>
//         </div>
//       </div>
//     </div>
//   );
// }

// // Activity Modal Component
// function ActivityModal({ onClose, onSave, activity, employees, mode }) {
//   const [formData, setFormData] = useState(activity || {
//     employeeId: '',
//     activityType: 'check_in',
//     action: '',
//     description: '',
//     location: 'Main Office',
//     device: 'Desktop',
//     duration: null
//   });

//   const handleSubmit = (e) => {
//     e.preventDefault();
//     const selectedEmployee = employees.find(emp => emp.id === parseInt(formData.employeeId));
//     const activityData = {
//       ...formData,
//       employeeName: selectedEmployee?.name,
//       employeeAvatar: selectedEmployee?.name.split(' ').map(n => n[0]).join(''),
//       department: selectedEmployee?.department
//     };
//     onSave(activityData);
//   };

//   const handleChange = (field, value) => {
//     setFormData(prev => ({ ...prev, [field]: value }));
//   };

//   const activityTypes = [
//     { value: 'check_in', label: 'Check In', icon: LogIn },
//     { value: 'check_out', label: 'Check Out', icon: LogOut },
//     { value: 'file_upload', label: 'File Upload', icon: Upload },
//     { value: 'coffee_break', label: 'Coffee Break', icon: Coffee },
//     { value: 'lunch_break', label: 'Lunch Break', icon: Coffee },
//     { value: 'smoking_break', label: 'Smoking Break', icon: Smoking },
//     { value: 'washroom_break', label: 'Washroom Break', icon: DoorOpen },
//     { value: 'prayer_break', label: 'Prayer Break', icon: Prayer },
//     { value: 'team_meeting', label: 'Team Meeting', icon: Users2 },
//     { value: 'hr_update', label: 'HR Update', icon: FileText },
//     { value: 'project_timeline', label: 'Project Timeline', icon: Target }
//   ];

//   return (
//     <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
//       <div className="bg-white rounded-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto">
//         <div className="flex justify-between items-center p-6 border-b border-gray-200 sticky top-0 bg-white">
//           <h3 className="text-lg font-semibold text-gray-900">
//             {mode === 'add' ? 'Log Employee Activity' : 'Edit Activity'}
//           </h3>
//           <button onClick={onClose} className="p-1 hover:bg-gray-100 rounded-lg">
//             <X className="h-5 w-5" />
//           </button>
//         </div>
        
//         <form onSubmit={handleSubmit} className="p-6 space-y-4">
//           <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
//             <div>
//               <label className="block text-sm font-medium text-gray-700 mb-1">Employee *</label>
//               <select 
//                 value={formData.employeeId}
//                 onChange={(e) => handleChange('employeeId', e.target.value)}
//                 required
//                 className="w-full px-3 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
//               >
//                 <option value="">Select Employee</option>
//                 {employees.map(emp => (
//                   <option key={emp.id} value={emp.id}>{emp.name} - {emp.department}</option>
//                 ))}
//               </select>
//             </div>
            
//             <div>
//               <label className="block text-sm font-medium text-gray-700 mb-1">Activity Type *</label>
//               <select 
//                 value={formData.activityType}
//                 onChange={(e) => handleChange('activityType', e.target.value)}
//                 required
//                 className="w-full px-3 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
//               >
//                 {activityTypes.map(type => (
//                   <option key={type.value} value={type.value}>{type.label}</option>
//                 ))}
//               </select>
//             </div>
//           </div>

//           <div>
//             <label className="block text-sm font-medium text-gray-700 mb-1">Action *</label>
//             <input 
//               type="text" 
//               value={formData.action}
//               onChange={(e) => handleChange('action', e.target.value)}
//               required
//               placeholder="e.g., Checked in, Started coffee break"
//               className="w-full px-3 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
//             />
//           </div>

//           <div>
//             <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
//             <textarea 
//               value={formData.description}
//               onChange={(e) => handleChange('description', e.target.value)}
//               rows="3"
//               placeholder="Describe the activity..."
//               className="w-full px-3 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
//             />
//           </div>

//           <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
//             <div>
//               <label className="block text-sm font-medium text-gray-700 mb-1">Location</label>
//               <select 
//                 value={formData.location}
//                 onChange={(e) => handleChange('location', e.target.value)}
//                 className="w-full px-3 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
//               >
//                 <option value="Main Office">Main Office</option>
//                 <option value="Remote">Remote</option>
//                 <option value="Break Room">Break Room</option>
//                 <option value="Conference Room">Conference Room</option>
//                 <option value="Cafeteria">Cafeteria</option>
//               </select>
//             </div>
            
//             <div>
//               <label className="block text-sm font-medium text-gray-700 mb-1">Device</label>
//               <select 
//                 value={formData.device}
//                 onChange={(e) => handleChange('device', e.target.value)}
//                 className="w-full px-3 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
//               >
//                 <option value="Desktop">Desktop</option>
//                 <option value="Laptop">Laptop</option>
//                 <option value="Mobile">Mobile</option>
//                 <option value="Tablet">Tablet</option>
//                 <option value="N/A">N/A</option>
//               </select>
//             </div>
//           </div>

//           <div>
//             <label className="block text-sm font-medium text-gray-700 mb-1">Duration (minutes)</label>
//             <input 
//               type="number" 
//               value={formData.duration ? formData.duration / 60 : ''}
//               onChange={(e) => handleChange('duration', e.target.value ? e.target.value * 60 : null)}
//               placeholder="e.g., 15 for 15 minutes"
//               className="w-full px-3 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
//             />
//           </div>

//           <div className="flex gap-3 pt-6 border-t border-gray-200">
//             <button 
//               type="button"
//               onClick={onClose}
//               className="flex-1 px-4 py-3 text-sm text-gray-700 bg-gray-100 rounded-xl hover:bg-gray-200 transition duration-200"
//             >
//               Cancel
//             </button>
//             <button 
//               type="submit"
//               className="flex-1 px-4 py-3 text-sm text-white bg-blue-600 rounded-xl hover:bg-blue-700 transition duration-200"
//             >
//               {mode === 'add' ? 'Log Activity' : 'Update Activity'}
//             </button>
//           </div>
//         </form>
//       </div>
//     </div>
//   );
// }

// // Helper functions (defined outside component)
// function getActivityColor(type) {
//   const colors = {
//     check_in: 'bg-green-100 text-green-800 border-green-200',
//     check_out: 'bg-red-100 text-red-800 border-red-200',
//     file_upload: 'bg-blue-100 text-blue-800 border-blue-200',
//     coffee_break: 'bg-orange-100 text-orange-800 border-orange-200',
//     smoking_break: 'bg-yellow-100 text-yellow-800 border-yellow-200',
//     washroom_break: 'bg-purple-100 text-purple-800 border-purple-200',
//     prayer_break: 'bg-indigo-100 text-indigo-800 border-indigo-200',
//     lunch_break: 'bg-pink-100 text-pink-800 border-pink-200',
//     team_meeting: 'bg-teal-100 text-teal-800 border-teal-200',
//     hr_update: 'bg-cyan-100 text-cyan-800 border-cyan-200',
//     project_timeline: 'bg-amber-100 text-amber-800 border-amber-200'
//   };
//   return colors[type] || 'bg-gray-100 text-gray-800 border-gray-200';
// }

// function getActivityIcon(type) {
//   const icons = {
//     check_in: <LogIn className="h-4 w-4" />,
//     check_out: <LogOut className="h-4 w-4" />,
//     file_upload: <Upload className="h-4 w-4" />,
//     coffee_break: <Coffee className="h-4 w-4" />,
//     smoking_break: <Smoking className="h-4 w-4" />,
//     washroom_break: <DoorOpen className="h-4 w-4" />,
//     prayer_break: <Prayer className="h-4 w-4" />,
//     lunch_break: <Coffee className="h-4 w-4" />,
//     team_meeting: <Users2 className="h-4 w-4" />,
//     hr_update: <FileText className="h-4 w-4" />,
//     project_timeline: <Target className="h-4 w-4" />
//   };
//   return icons[type] || <Clock className="h-4 w-4" />;
// }

// function formatDuration(seconds) {
//   if (!seconds) return null;
//   const minutes = Math.floor(seconds / 60);
//   return `${minutes}m`;
// }

// export default TimeTracker;